name: UntiUtils
main: com.untistore.utils.Main
version: 1.0
author: Jacksmf
description: A Utils plugin
commands:
  gamemode:
    description: change gamemode
    usage: /<command>
    aliases: [ gmc, gms, gma, gmsp ]
    permission: untiutils.gamemode.*
  tp:
    description: teleport to player or coordinates
    usage: /<command> <player> | <x> <y> <z>
    aliases: [ teleport ]
    permission: untiutils.tp.*
  vanish:
    description: This will make the player invisible to the other players (except for the admins and the player itself)
    usage: /<command>
    aliases: [ v ]
    permission: untiutils.vanish
  lockdown:
    description: This will enable the lockdown mode, Lockdown makes it so players can't break, or place blocks or join
    usage: /<command>
    aliases: [ lock ]
    permission: untiutils.lockdown.*
  lobby:
    description: Teleport to the lobby of the server
    usage: /<command>
    aliases: [ spawn, hub ]

permissions:
  untiutils.gamemode.*:
    description: Gives access to all gamemode commands
    children:
      untiutils.gamemode.gmc: true
      untiutils.gamemode.gms: true
      untiutils.gamemode.gma: true
      untiutils.gamemode.gmsp: true
  untiutils.tp.*:
    description: Gives access to all teleport commands
    children:
      untiutils.tp.tp: true
      untiutils.tp.tp.others: true
  untiutils.vanish:
    description: Gives access to vanish command
  untiutils.lockdown.*:
    description: Gives access to all lockdown commands and options
    children:
      untiutils.lockdown.on: true
      untiutils.lockdown.off: true